#!/usr/bin/env julia

using Gridap
using GridapGmsh
using Gridap.Geometry: add_tag!, get_cell_coordinates, get_face_entity,
    get_face_labeling, get_faces, get_node_coordinates, get_vertex_coordinates,
    get_tag_from_name, num_cells, get_cell_node_ids
using Gridap.Algebra: NLSolver
using LineSearches: BackTracking
using LinearAlgebra
using Statistics: mean
using Printf

"""
    tag_boundaries!(model; tol=1e-6)

For a 3D bar mesh generated by Gmsh, tag the boundary at x = xmin as "left"
and the boundary at x = xmax as "right".
"""
function tag_boundaries!(model; tol=1.0e-6)
    labels = get_face_labeling(model)
    topo = model.grid_topology
    xs = map(p -> p[1], get_vertex_coordinates(topo))
    xmin, xmax = minimum(xs), maximum(xs)

    face_labels = labels.d_to_dface_to_entity[3]
    edge_labels = labels.d_to_dface_to_entity[2]
    vert_labels = labels.d_to_dface_to_entity[1]
    fill!(face_labels, 0)
    fill!(edge_labels, 0)
    fill!(vert_labels, 0)
    empty!(labels.tag_to_entities)
    empty!(labels.tag_to_name)

    face_to_vertices = get_faces(topo, 2, 0)
    face_to_edges = get_faces(topo, 2, 1)
    vertex_coords = get_vertex_coordinates(topo)
    right_id = Int32(1)
    left_id  = Int32(2)

    for (i, verts) in enumerate(face_to_vertices)
        xs_face = map(v -> vertex_coords[v][1], verts)
        if all(x -> isapprox(x, xmax; atol=tol), xs_face)
            face_labels[i] = right_id
            for e in face_to_edges[i]
                edge_labels[e] = right_id
            end
            for v in verts
                vert_labels[v] = right_id
            end
        elseif all(x -> isapprox(x, xmin; atol=tol), xs_face)
            face_labels[i] = left_id
            for e in face_to_edges[i]
                edge_labels[e] = left_id
            end
            for v in verts
                vert_labels[v] = left_id
            end
        end
    end

    push!(labels.tag_to_entities, [right_id])
    push!(labels.tag_to_name, "right")
    push!(labels.tag_to_entities, [left_id])
    push!(labels.tag_to_name, "left")
end

"""
    run_gridap(mesh_file)

Solve the 3D bar problem with finite-strain Neo-Hookean hyperelasticity
and surface traction. Returns `(coords, displacements, times)`.
"""
function run_gridap(mesh_file::AbstractString)
    # ---- material & load ----
    # Units: mm and MPa (steel ~210 GPa = 210e3 MPa)
    E, ν = 210e3, 0.3
    λ = E * ν / ((1 + ν) * (1 - 2 * ν))
    μ = E / (2 * (1 + ν))

    # Example: 10 MPa traction in the y direction (bar: 100 x 10 x 10 mm)
    # traction_value = 10.0
    traction_value = 0.01
    tvec = VectorValue(0.0, traction_value, 0.0)
    load_factors = collect(0.05:0.05:1.0)  # Fine load increments

    t0_total = time()

    # ---- model & measures ----
    model = GmshDiscreteModel(mesh_file)
    tag_boundaries!(model)
    labels = get_face_labeling(model)
    left_ids = get_tag_from_name(labels, "left")
    right_ids = get_tag_from_name(labels, "right")

    Ω = Triangulation(model)
    Γ_left = BoundaryTriangulation(model, tags = "left")
    Γ_right = BoundaryTriangulation(model, tags = "right")
    nodes_left = length(unique(vcat(get_cell_node_ids(Γ_left)...)))
    nodes_right = length(unique(vcat(get_cell_node_ids(Γ_right)...)))
    println("Boundary tags: left=", left_ids, " (nodes=", nodes_left, "), right=", right_ids, " (nodes=", nodes_right, ")")
    node_points = get_node_coordinates(model)

    # Use roughly 3rd-order quadrature for 3D elements (adjust if needed)
    dΩ = Measure(Ω, 3)
    dΓ_right = Measure(Γ_right, 2)

    # ---- FE spaces ----
    reffe = ReferenceFE(lagrangian, VectorValue{3, Float64}, 1)
    V0 = TestFESpace(model, reffe;
                     conformity = :H1,
                     dirichlet_tags = ["left"])  # Fix the left end
    U = TrialFESpace(V0)  # Default Dirichlet data = 0

    # ---- Neo-Hookean hyperelastic helpers (Total Lagrange) ----

    # Second-order identity tensor
    I = one(TensorValue{3,3,Float64})

    # Deformation gradient F, right Cauchy-Green C, volume J
    F(∇u) = I + ∇u
    C(Fx) = transpose(Fx) ⋅ Fx
    J(Fx) = det(Fx)

    # Variation of Green-Lagrange strain dE(δu)
    dE(∇δu, ∇u) = 0.5 * ( ∇δu ⋅ F(∇u) + (∇δu ⋅ F(∇u))' )

    # 2nd Piola-Kirchhoff stress S(C) (compressible Neo-Hookean)
    function S(∇u)
        Fx = F(∇u)
        Cx = C(Fx)
        Cinv = inv(Cx)
        Jx = sqrt ∘ det(Cx)            # J = sqrt(det(C))
        μ*(I - Cinv) + λ * (log ∘ Jx) * Cinv
    end

    # Double contraction A:B
    dc(A,B) = inner(A,B)

    # Variation of S: dS : dE (material part of tangent stiffness)
    function dS(∇δu, ∇u)
        Fx = F(∇u)
        Cx = C(Fx)
        Cinv = inv(Cx)
        Jx = sqrt ∘ det(Cx)
        _dE = dE(∇δu, ∇u)
        λ * dc(Cinv,_dE) * Cinv + 2 * (μ - λ * (log ∘ Jx)) * Cinv ⋅ _dE ⋅ transpose(Cinv)
    end

    # ---- weak form: residual & jacobian ----

    lf = Ref(1.0)  # Load factor
    # Internal virtual work - external virtual work = 0
    res(uh, v) =
        ∫( dc( dE(∇(v), ∇(uh)), S(∇(uh)) ) )dΩ -
        lf[] * ∫( inner(tvec, v) )dΓ_right

    # Material nonlinearity part
    jac_mat(uh, du, v) =
        ∫( dc( dE(∇(v), ∇(uh)), dS(∇(du), ∇(uh)) ) )dΩ

    # Geometric nonlinearity part (S with ∇du coupling)
    jac_geo(uh, du, v) =
        ∫( dc( ∇(v), S(∇(uh)) ⋅ ∇(du) ) )dΩ

    jac(uh, du, v) = jac_mat(uh, du, v) + jac_geo(uh, du, v)

    # ---- assemble operator ----
    t_asm = @elapsed begin
        op = FEOperator(res, jac, U, V0)
    end

    # ---- nonlinear solve (Newton) ----
    nls = NLSolver(
        method = :newton,
        show_trace = true,
        linesearch = BackTracking(),
        ftol = 1.0e-6,
        iterations = 40,
    )
    solver = FESolver(nls)

    # Initial guess = zero displacement
    x0 = zeros(Float64, num_free_dofs(V0))
    uh0 = FEFunction(U, x0)

    t_solve = @elapsed begin
        uh = uh0
        for f in load_factors
            lf[] = f
            uh, _ = solve!(uh, solver, op)
            max_step_u = maximum(p -> norm(uh(p)), node_points)
            @printf "  load factor %.2f solved, max|u|=%.3e\n" f max_step_u
        end
        global uh_final = uh  # Keep for external access (debug option)
    end

    t_total = time() - t0_total

    # ---- collect nodal displacements ----
    coords = node_points
    coord_array = zeros(length(coords), 3)
    u_array = zeros(length(coords), 3)
    max_u = 0.0
    for (i, p) in enumerate(coords)
        coord_array[i, :] .= Tuple(p)
        val = uh_final(p)
        u_array[i, :] .= Tuple(val)
        max_u = max(max_u, norm(val))
    end

    @printf "[Gridap Neo-Hookean] Total: %.3fs | Assembly: %.3fs | Solve: %.3fs | max|u|=%.3e\n" t_total t_asm t_solve max_u

    # Uncomment if you want VTK output for visualization
    vtk_dir = "neo_hookean_output"
    mkpath(vtk_dir)
    J_field = p -> J(F(∇(uh_final)(p)))  # Output volume ratio det(F)
    # Node scalar for tagged regions (right: 1, left: -1, interior: 0)
    tag_values = zeros(length(node_points))
    for nid in vcat(get_cell_node_ids(Γ_right)...)
        tag_values[nid] = 1.0
    end
    for nid in vcat(get_cell_node_ids(Γ_left)...)
        tag_values[nid] = -1.0
    end
    cell_tags = zeros(length(get_cell_node_ids(Ω)))
    for (cid, node_ids) in enumerate(get_cell_node_ids(Ω))
        cell_tags[cid] = mean(tag_values[node_ids])
    end
    writevtk(Ω, joinpath(vtk_dir, "neo_hookean_bar"),
             cellfields = ["displacement" => uh_final, "J" => J_field],
             celldata = ["tag" => cell_tags])
    write_deformed_vtu(model, uh_final; dir=vtk_dir, basename="neo_hookean_bar_deformed", scale=1.0, J_field=J_field, cell_tags=cell_tags)

    return coord_array, u_array, (t_total, t_asm, t_solve)
end

function main(args)
    mesh_file = get(args, 1, "tension_bar.msh")
    run_gridap(mesh_file)
end

# Write VTK with scaled displacement and extra fields
function write_deformed_vtu(model, uh; dir="neo_hookean_output", basename="neo_hookean_bar_deformed", scale=1.0, J_field=nothing, cell_tags=nothing)
    Ω = Triangulation(model)
    uh_scaled = scale * uh
    x_def = p -> p + uh_scaled(p)  # Deformed coordinate field
    mkpath(dir)
    cfields = Dict{String,Any}("displacement" => uh_scaled, "deformed_coords" => x_def)
    if J_field !== nothing
        cfields["J"] = J_field
    end
    kwargs = Dict{Symbol,Any}(:cellfields => collect(pairs(cfields)))
    if cell_tags !== nothing
        kwargs[:celldata] = ["tag" => cell_tags]
    end
    writevtk(Ω, joinpath(dir, basename); kwargs...)
end

if abspath(PROGRAM_FILE) == @__FILE__
    main(ARGS)
end
