from __future__ import annotations

import importlib

__all__ = [
    "FESpaceBase",
    "FESpace",
    "FESpacePytree",
    "NamedSpace",
    "BilinearSpaces",
    "LinearSpaces",
    "ResidualSpaces",
    "JacobianSpaces",
    "Expr",
    "FieldRef",
    "TrialRef",
    "TestRef",
    "UnknownRef",
    "ZeroRef",
    "ParamRef",
    "trial_ref",
    "test_ref",
    "param_ref",
    "unknown_ref",
    "zero_ref",
    "Params",
    "LinearForm",
    "BilinearForm",
    "ResidualForm",
    "MixedResidualBinding",
    "bind_mixed_residual",
    "MixedWeakForm",
    "make_mixed_residuals",
    "kernel",
    "MixedFESpace",
    "MixedSpace",
    "MixedSpaces",
    "MixedRoleFESpace",
    "MixedRoleSpaces",
    "build_mixed_role_block_system",
    "MixedProblem",
    "MixedDirichletBC",
    "MixedBlockSystem",
    "MixedRoleBlockSystem",
    "MixedRoleCondensedSystem",
    "compile_bilinear",
    "compile_linear",
    "compile_residual",
    "assemble_bilinear_form_pg",
    "compile_surface_linear",
    "compile_surface_bilinear",
    "compile_mixed_surface_residual",
    "compile_mixed_residual",
    "FormContext",
    "MixedFormContext",
    "VolumeContext",
    "SurfaceContext",
    "FieldPair",
    "ElementVector",
    "vector_load_form",
    "build_form_contexts_pair",
    "make_space",
    "make_space_pytree",
    "make_hex_basis",
    "make_hex_basis_pytree",
    "make_hex_space",
    "make_hex_space_pytree",
    "make_hex20_basis",
    "make_hex20_basis_pytree",
    "make_hex20_space",
    "make_hex20_space_pytree",
    "make_hex27_basis",
    "make_hex27_basis_pytree",
    "make_hex27_space",
    "make_hex27_space_pytree",
    "make_tet_basis",
    "make_tet_basis_pytree",
    "make_tet_space",
    "make_tet_space_pytree",
    "make_tet10_basis",
    "make_tet10_basis_pytree",
    "make_tet10_space",
    "make_tet10_space_pytree",
    "MeshData",
    "BasisData",
    "SpaceData",
    "make_element_residual_kernel",
    "make_element_bilinear_kernel",
    "make_element_linear_kernel",
    "make_element_jacobian_kernel",
    "make_element_kernel",
    "AssemblyPolicy",
    "assemble_bilinear_form",
    "assemble_linear_form",
    "assemble_residual",
    "assemble_jacobian",
    "element_residual",
    "element_jacobian",
    "make_sparsity_pattern",
    "chunk_pad_stats",
    "BatchedAssembler",
    "assemble_functional",
    "assemble_mass_matrix",
    "active_dofs_from_full_dofs",
    "active_dofs_from_full_dofs",
    "CraigBamptonBasis",
    "ContactSearchManagerLike",
    "FrictionManagerLike",
    "LinearConstraintSystem",
    "RBE3Patch",
    "RBE2RemoteFixture",
    "RBE3RemoteFixture",
    "ReducedContactPair",
    "ReducedContactPairAdapter",
    "ReducedContactPairDofs",
    "ReducedCoupledSystem",
    "ReducedCoupledSystemBuilder",
    "ReducedEquationBuilder",
    "NonlinearReducedFEModel",
    "ReducedEquationField",
    "ReducedEquationProblem",
    "ReducedEquationSolveInfo",
    "make_reduced_equation_newmark_residual",
    "reduced_equation_active_newmark_step",
    "reduced_equation_newmark_step",
    "solve_reduced_equation_active",
    "ReducedContactDynamics",
    "ReducedLinearConstraintSystem",
    "ReferencePointFixture",
    "ActiveContactState",
    "ActiveContactIterationRecord",
    "ActiveContactNewmarkStepInfo",
    "ActiveContactSolveInfo",
    "ContactAABBIndex",
    "ContactCandidateSet",
    "ContactKinematics",
    "ContactNeighborList",
    "ContactSearchCache",
    "ContactUpdateSnapshot",
    "FrictionalContactUpdateSnapshot",
    "NewmarkConfig",
    "NewmarkState",
    "NewmarkStepInfo",
    "ProjectedReducedOperator",
    "ScipyCraigBamptonBasis",
    "ScipyProjectedReducedOperator",
    "NodeSurfaceContactKinematics",
    "NodeSurfaceContactSearchManager",
    "NodeSurfacePenaltyContact",
    "PairedContactKinematics",
    "PairedPenaltyContact",
    "PlanePenaltyContact",
    "SurfaceQuadratureContactKinematics",
    "SurfaceQuadratureContactSearchManager",
    "SurfaceQuadraturePenaltyContact",
    "TangentialPenaltyHistory",
    "TangentialPenaltyFrictionManager",
    "active_contact_fixed_point_solve",
    "active_contact_newmark_step",
    "assemble_reference_fixture_preload",
    "complement_dofs",
    "fixed_interface_modes",
    "integrate_newmark",
    "make_average_rigid_body_constraint",
    "make_craig_bampton_basis",
    "make_newmark_effective_residual",
    "make_unilateral_plane_contact_residual",
    "newmark_kinematics",
    "newmark_step",
    "node_surface_contact_kinematics_from_surfaces",
    "orthonormal_tangent_basis",
    "paired_contact_kinematics_from_surfaces",
    "plane_contact_kinematics_from_surface",
    "compose_residuals",
    "contact_aabb_index_from_surface",
    "contact_candidate_set_from_bounding_boxes",
    "contact_candidate_set_from_per_contact",
    "contact_search_cache_from_kinematics",
    "friction_residual_from_history",
    "make_friction_residual",
    "make_node_surface_contact_search_manager",
    "make_surface_quadrature_contact_search_manager",
    "node_surface_candidate_set_from_aabb_index",
    "node_surface_candidate_set_from_bounding_boxes",
    "node_surface_neighbor_list_from_aabb_index",
    "node_surface_neighbor_list_from_bounding_boxes",
    "reduced_jacobian_from_full",
    "reduced_residual_from_full",
    "linear_constraint_system_from_reference_fixtures",
    "make_average_rigid_body_constraint",
    "solve_linear_constraint_kkt",
    "retained_dofs_from_surface",
    "solve_constraint_modes",
    "slip_norm",
    "stick_count",
    "surface_quadrature_contact_kinematics_from_surfaces",
    "surface_quadrature_candidate_set_from_aabb_index",
    "surface_quadrature_neighbor_list_from_aabb_index",
    "update_active_contact_state",
    "update_tangential_penalty_history",
    "vector_dofs_from_nodes",
    "scalar_body_force_form",
    "make_scalar_body_force_form",
    "vector_body_force_form",
    "linear_elasticity_form",
    "constant_body_force_form",
    "constant_body_force_vector_form",
    "diffusion_form",
    "BEAM_DOF_PER_NODE",
    "BeamSection",
    "assemble_beam_mass",
    "assemble_beam_point_load",
    "assemble_beam_point_loads",
    "assemble_beam_stiffness",
    "assemble_beam_uniform_load",
    "beam_element_dofs",
    "beam_element_mass_global",
    "beam_element_mass_local",
    "beam_element_stiffness_global",
    "beam_element_stiffness_local",
    "beam_element_uniform_load_global",
    "beam_element_uniform_load_local",
    "beam_node_dofs",
    "structured_beam_chain",
    "TRUSS_DOF_PER_NODE",
    "TrussSection",
    "assemble_truss_mass",
    "assemble_truss_stiffness",
    "structured_truss_chain",
    "truss_element_dofs",
    "truss_element_mass_global",
    "truss_element_stiffness_global",
    "truss_node_dofs",
    "assemble_dof_dashpot",
    "assemble_dof_spring",
    "assemble_nodal_load",
    "assemble_rayleigh_damping",
    "rayleigh_coefficients_from_modal_damping",
    "rayleigh_damping_ratio",
    "right_cauchy_green",
    "green_lagrange_strain",
    "deformation_gradient",
    "pk2_neo_hookean",
    "neo_hookean_residual_form",
    "StokesSpaces",
    "make_stokes_spaces",
    "HexMesh",
    "HexMeshPytree",
    "StructuredHexBox",
    "SurfaceMesh",
    "SurfaceMeshPytree",
    "SurfaceWithElemConn",
    "surface_with_elem_conn",
    "SurfaceFormField",
    "SurfaceFormContext",
    "SurfaceBilinearContext",
    "SurfaceSupermesh",
    "vector_surface_load_form",
    "make_vector_surface_load_form",
    "assemble_surface_linear_form",
    "assemble_surface_bilinear_form",
    "ContactCouplingMatrix",
    "assemble_contact_coupling_matrices",
    "assemble_contact_onesided_floor",
    "assemble_contact_interface_residual",
    "assemble_contact_interface_jacobian",
    "map_surface_facets_to_tet_elements",
    "map_surface_facets_to_hex_elements",
    "tri_area",
    "tri_quadrature",
    "facet_triangles",
    "facet_shape_values",
    "volume_shape_values_at_points",
    "quad_shape_and_local",
    "quad9_shape_values",
    "hex27_gradN",
    "ContactSideSpec",
    "PreparedContactInterface",
    "ContactSurfaceSpace",
    "ContactPairSpec",
    "ContactSpaces",
    "ContactGroupSpec",
    "ContactGroupSpaces",
    "OneSidedContactSpec",
    "OneSidedContactSpaces",
    "ContactSide",
    "ContactOperators",
    "PenaltyContactContribution",
    "MultiplierContactContribution",
    "ContactState",
    "AugmentedLagrangianState",
    "AugmentedLagrangianResult",
    "MultiplierSpec",
    "ContactMultiplierSpace",
    "coarse_p1_basis_from_node_groups",
    "coarse_p1_basis_from_surface_grid",
    "ContactKKTSolveConfig",
    "EmbeddingMap",
    "build_nodal_embedding_map",
    "build_barycentric_embedding_map",
    "build_barycentric_embedding_map_from_meshes",
    "assemble_embedding_constraint_matrix",
    "assemble_fixed_rigid_hub_constraint_matrix",
    "assemble_rigid_hub_constraint_matrix",
    "assemble_rbe2_constraint_matrix",
    "assemble_rbe3_constraint_matrix",
    "build_rbe3_weights",
    "build_rbe3_remote_resultant",
    "OneSidedContact",
    "PreparedOneSidedContactInterface",
    "OneSidedContactSurfaceSpace",
    "PreparedOneToManyContactInterface",
    "OneToManyContactSurfaceSpace",
    "assemble_contact_constraint_operators",
    "assemble_multiplier",
    "assemble_contact_operators",
    "assemble_contact_penalty_operators",
    "assemble_penalty",
    "assemble_contact_interface_residual",
    "assemble_contact_interface_jacobian",
    "assemble_contact_coupling_matrices",
    "assemble_contact_kkt",
    "solve_contact_kkt",
    "solve_augmented_lagrangian_outer_loop",
    "ContactSolveResult",
    "update_contact_state_penalty",
    "solve_contact_penalty_jax",
    "solve_contact_al_jax",
    "facet_gap_values",
    "active_contact_facets",
    "tag_axis_minmax_facets",
    "load_gmsh_mesh",
    "load_gmsh_hex_mesh",
    "load_gmsh_tet_mesh",
    "make_surface_from_facets",
    "build_surface_supermesh",
    "ContactCouplingMatrix",
    "assemble_contact_coupling_matrices",
    "assemble_contact_interface_residual",
    "assemble_contact_interface_jacobian",
    "map_surface_facets_to_tet_elements",
    "TetMesh",
    "TetMeshPytree",
    "StructuredTetBox",
    "StructuredTetTensorBox",
    "BaseMeshPytree",
    "SurfaceWithFacetMap",
    "bbox_predicate",
    "plane_predicate",
    "axis_plane_predicate",
    "slab_predicate",
    "HexTriLinearBasis",
    "HexTriLinearBasisPytree",
    "HexSerendipityBasis20",
    "HexSerendipityBasis20Pytree",
    "HexTriQuadraticBasis27",
    "HexTriQuadraticBasis27Pytree",
    "TetLinearBasis",
    "TetLinearBasisPytree",
    "TetQuadraticBasis10",
    "TetQuadraticBasis10Pytree",
    "lame_parameters",
    "isotropic_3d_D",
    "spdirect_solve_cpu",
    "spdirect_solve_gpu",
    "spdirect_solve_jax",
    "ReducedDenseKktFactorization",
    "factor_reduced_dense_kkt_jax",
    "make_reduced_dense_factorized_solver_jax",
    "make_reduced_rhs_projector_jax",
    "pack_reduced_kkt_rhs",
    "project_reduced_rhs_cpu",
    "project_reduced_rhs_jax",
    "solve_reduced_dense_batch_jax",
    "solve_reduced_dense_batch_jax_factorized",
    "coo_to_csr",
    "SparsityPattern",
    "FluxSparseMatrix",
    "FluxSparseOperator",
    "FluxBlockMatrix",
    "coalesce_coo",
    "concat_flux",
    "block_diag_flux",
    "build_block_system",
    "split_block_matrix",
    "BlockSystem",
    "CoupledSystem",
    "CoupledSystemBuilder",
    "NumpyCoupledSystem",
    "NumpyCoupledSystemBuilder",
    "JAXCoupledSystem",
    "JAXCoupledSystemBuilder",
    "make_coupled_system",
    "make_coupled_system_builder",
    "make_jax_coupled_system",
    "make_jax_coupled_system_builder",
    "make_numpy_coupled_system",
    "make_numpy_coupled_system_builder",
    "DirichletSpec",
    "ConstraintSpec",
    "LinearSolver",
    "NonlinearSolver",
    "NewmarkResult",
    "newmark_solve_linear",
    "petsc_solve",
    "petsc_shell_solve",
    "petsc_is_available",
    "DirichletBC",
    "enforce_dirichlet_dense",
    "enforce_dirichlet_dense_jax",
    "enforce_dirichlet_fluxsparse",
    "enforce_dirichlet_sparse",
    "enforce_dirichlet_system",
    "split_dirichlet_matrix",
    "free_dofs",
    "condense_dirichlet_fluxsparse",
    "condense_dirichlet_fluxsparse_coo",
    "condense_dirichlet_dense",
    "restrict_flux_to_free",
    "expand_dirichlet_solution",
    "condense_dirichlet_system",
    "cg_solve",
    "make_block_jacobi_preconditioner",
    "build_cg_operator",
    "CGOperator",
    "NonlinearAnalysis",
    "NewtonLoopConfig",
    "LoadStepResult",
    "NewtonSolveRunner",
    "constrained_kkt_config",
    "solve_nonlinear",
    "NonlinearConstrainedProblem",
    "NonlinearConstrainedSolveResult",
    "solve_nonlinear_constrained_kkt",
    "LinearAnalysis",
    "LinearSolveConfig",
    "LinearStepResult",
    "LinearSolveRunner",
    "newton_solve",
    "newton_solve_jax",
    "NewtonJaxResult",
    "ActiveContactIterationRecord",
    "ActiveContactNewmarkStepInfo",
    "ActiveContactSolveInfo",
    "ContactSearchManagerLike",
    "CraigBamptonBasis",
    "FrictionManagerLike",
    "LinearConstraintSystem",
    "NewmarkConfig",
    "NewmarkState",
    "NewmarkStepInfo",
    "ProjectedReducedOperator",
    "ScipyCraigBamptonBasis",
    "ScipyProjectedReducedOperator",
    "RBE3Patch",
    "RBE2RemoteFixture",
    "RBE3RemoteFixture",
    "ReducedContactPair",
    "ReducedContactPairAdapter",
    "ReducedContactPairDofs",
    "ReducedCoupledSystem",
    "ReducedCoupledSystemBuilder",
    "ReducedEquationBuilder",
    "ReducedEquationField",
    "ReducedEquationProblem",
    "ReducedEquationSolveInfo",
    "make_reduced_equation_newmark_residual",
    "reduced_equation_active_newmark_step",
    "reduced_equation_newmark_step",
    "solve_reduced_equation_active",
    "ReducedContactDynamics",
    "ReducedLinearConstraintSystem",
    "ReferencePointFixture",
    "active_contact_fixed_point_solve",
    "active_contact_newmark_step",
    "assemble_reference_fixture_preload",
    "complement_dofs",
    "fixed_interface_modes",
    "integrate_newmark",
    "linear_constraint_system_from_reference_fixtures",
    "make_average_rigid_body_constraint",
    "make_craig_bampton_basis",
    "make_newmark_effective_residual",
    "newmark_kinematics",
    "newmark_step",
    "project_constraints_through_basis",
    "remote_reference_direction",
    "remote_reference_size",
    "retained_dofs_from_node_masks",
    "retained_dofs_from_node_sets",
    "rbe3_remote_reference_rank",
    "reduced_jacobian_from_full",
    "reduced_residual_from_full",
    "make_reduced_equation_newmark_residual",
    "reduced_equation_active_newmark_step",
    "reduced_equation_newmark_step",
    "solve_linear_constraint_kkt",
    "solve_constraint_modes",
    "solve_reduced_equation_active",
    "solve_reduced_equation",
    "validate_rbe3_remote_reference_rank",
    "write_vtu",
    "write_displacement_vtu",
    "make_jitted_residual",
    "make_jitted_jacobian",
    "block",
    "make_elastic_point_data",
    "write_elastic_vtu",
    "make_point_data_displacement",
    "write_point_data_vtu",
    "principal_stresses",
    "principal_sum",
    "max_shear_stress",
    "von_mises_stress",
]

_PHYSICS_EXPORTS = {
    "lame_parameters",
    "isotropic_3d_D",
    "linear_elasticity_form",
    "vector_body_force_form",
    "constant_body_force_vector_form",
    "diffusion_form",
    "BEAM_DOF_PER_NODE",
    "BeamSection",
    "assemble_beam_mass",
    "assemble_beam_point_load",
    "assemble_beam_point_loads",
    "assemble_beam_stiffness",
    "assemble_beam_uniform_load",
    "beam_element_dofs",
    "beam_element_mass_global",
    "beam_element_mass_local",
    "beam_element_stiffness_global",
    "beam_element_stiffness_local",
    "beam_element_uniform_load_global",
    "beam_element_uniform_load_local",
    "beam_node_dofs",
    "structured_beam_chain",
    "TRUSS_DOF_PER_NODE",
    "TrussSection",
    "assemble_truss_mass",
    "assemble_truss_stiffness",
    "structured_truss_chain",
    "truss_element_dofs",
    "truss_element_mass_global",
    "truss_element_stiffness_global",
    "truss_node_dofs",
    "assemble_dof_dashpot",
    "assemble_dof_spring",
    "assemble_nodal_load",
    "assemble_rayleigh_damping",
    "rayleigh_coefficients_from_modal_damping",
    "rayleigh_damping_ratio",
    "right_cauchy_green",
    "green_lagrange_strain",
    "deformation_gradient",
    "pk2_neo_hookean",
    "neo_hookean_residual_form",
    "make_elastic_point_data",
    "write_elastic_vtu",
    "make_point_data_displacement",
    "write_point_data_vtu",
    "interpolate_at_points",
    "principal_stresses",
    "principal_sum",
    "max_shear_stress",
    "von_mises_stress",
}

_TOOLS_VIS_EXPORTS = {
    "write_vtu",
    "write_displacement_vtu",
}

_TOOLS_JIT_EXPORTS = {
    "make_jitted_residual",
    "make_jitted_jacobian",
}

_CORE_EXPORTS = set(__all__) - _PHYSICS_EXPORTS - _TOOLS_VIS_EXPORTS - _TOOLS_JIT_EXPORTS


def __getattr__(name: str):
    if name in _PHYSICS_EXPORTS:
        module = importlib.import_module(".physics", __name__)
    elif name in _TOOLS_VIS_EXPORTS:
        module = importlib.import_module(".tools.visualizer", __name__)
    elif name in _TOOLS_JIT_EXPORTS:
        module = importlib.import_module(".tools.jit", __name__)
    elif name in _CORE_EXPORTS:
        module = importlib.import_module(".core", __name__)
    else:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")

    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__():
    return sorted(set(globals()) | set(__all__))


try:
    from importlib.metadata import version, PackageNotFoundError
except ImportError:
    from importlib_metadata import version, PackageNotFoundError


def read_version_from_pyproject():
    import pathlib
    import re

    here = pathlib.Path(__file__).resolve()
    for root in here.parents:
        pyproject_path = root / "pyproject.toml"
        if pyproject_path.exists():
            content = pyproject_path.read_text()
            match = re.search(r'version\s*=\s*"(.*?)"', content)
            if match:
                return match.group(1)
    return None


def get_version(package_name):
    local_version = read_version_from_pyproject()
    if local_version is not None:
        return local_version
    try:
        return version(package_name)
    except PackageNotFoundError:
        return "0.0.0"


__version__ = get_version("fluxfem")
